-- Features Schema Migration for Supabase (PostgreSQL)

-- 6. AI Assistants
CREATE TABLE IF NOT EXISTS ai_assistants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  specialization TEXT,
  instructions TEXT,
  model TEXT DEFAULT 'gpt-4',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Checklist Folders
CREATE TABLE IF NOT EXISTS checklist_folders (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  organization_id BIGINT NOT NULL REFERENCES organizations(id),
  parent_id UUID REFERENCES checklist_folders(id),
  name TEXT NOT NULL,
  slug TEXT,
  path TEXT,
  created_by UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Checklist Templates
CREATE TABLE IF NOT EXISTS checklist_templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT,
  created_by TEXT,
  created_by_user_id UUID REFERENCES users(id),
  organization_id BIGINT REFERENCES organizations(id),
  is_public BOOLEAN DEFAULT false,
  is_category_folder BOOLEAN DEFAULT false,
  folder_color TEXT,
  folder_icon TEXT,
  parent_category_id BIGINT REFERENCES checklist_templates(id),
  folder_id UUID REFERENCES checklist_folders(id),
  display_order INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Checklist Fields
CREATE TABLE IF NOT EXISTS checklist_fields (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_id BIGINT NOT NULL REFERENCES checklist_templates(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  field_type TEXT NOT NULL,
  is_required BOOLEAN DEFAULT false,
  options TEXT, -- JSON armazenado como texto ou poderia ser JSONB
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. Inspections
CREATE TABLE IF NOT EXISTS inspections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  location TEXT,
  inspector_name TEXT,
  inspector_email TEXT,
  company_name TEXT,
  cep TEXT,
  address TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  scheduled_date DATE,
  completed_date DATE,
  status TEXT DEFAULT 'pendente',
  priority TEXT DEFAULT 'media',
  created_by UUID REFERENCES users(id),
  organization_id BIGINT REFERENCES organizations(id),
  responsible_name TEXT,
  responsible_email TEXT,
  inspector_signature TEXT,
  responsible_signature TEXT,
  action_plan TEXT,
  action_plan_type TEXT,
  ai_assistant_id BIGINT REFERENCES ai_assistants(id),
  
  -- Metadata Anti-Fraude
  started_at_user_time TIMESTAMPTZ,
  started_at_server_time TIMESTAMPTZ DEFAULT NOW(),
  location_start_lat DOUBLE PRECISION,
  location_start_lng DOUBLE PRECISION,
  location_end_lat DOUBLE PRECISION,
  location_end_lng DOUBLE PRECISION,
  device_fingerprint TEXT,
  device_model TEXT,
  device_os TEXT,
  is_offline_sync BOOLEAN DEFAULT false,
  sync_timestamp TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 11. Inspection Items
CREATE TABLE IF NOT EXISTS inspection_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  category TEXT,
  item_description TEXT,
  is_compliant BOOLEAN,
  observations TEXT,
  photo_url TEXT,
  template_id BIGINT REFERENCES checklist_templates(id),
  field_responses TEXT, -- JSON storage
  ai_pre_analysis TEXT,
  ai_action_plan TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 12. Action Items (Planos de Ação)
CREATE TABLE IF NOT EXISTS action_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  inspection_item_id BIGINT REFERENCES inspection_items(id),
  title TEXT NOT NULL,
  what_description TEXT,
  where_location TEXT,
  why_reason TEXT,
  how_method TEXT,
  who_responsible TEXT,
  when_deadline DATE,
  how_much_cost TEXT,
  status TEXT DEFAULT 'pending',
  priority TEXT DEFAULT 'media',
  is_ai_generated BOOLEAN DEFAULT false,
  assigned_to UUID REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. Inspection Media
CREATE TABLE IF NOT EXISTS inspection_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  inspection_item_id BIGINT REFERENCES inspection_items(id),
  media_type TEXT NOT NULL,
  file_name TEXT,
  file_url TEXT,
  file_size BIGINT,
  mime_type TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 14. Inspection Logs (Auditoria LGPD)
CREATE TABLE IF NOT EXISTS inspection_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inspection_id BIGINT NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id),
  action TEXT NOT NULL CHECK(action IN ('CREATE', 'UPDATE', 'DELETE', 'FINALIZE', 'REOPEN')),
  field_changed TEXT,
  old_value TEXT,
  new_value TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Índices Features
CREATE INDEX IF NOT EXISTS idx_checklist_fields_template ON checklist_fields(template_id);
CREATE INDEX IF NOT EXISTS idx_inspection_items_inspection ON inspection_items(inspection_id);
CREATE INDEX IF NOT EXISTS idx_action_items_inspection ON action_items(inspection_id);
CREATE INDEX IF NOT EXISTS idx_inspection_media_inspection ON inspection_media(inspection_id);
CREATE INDEX IF NOT EXISTS idx_inspections_created_by ON inspections(created_by);
CREATE INDEX IF NOT EXISTS idx_inspections_organization ON inspections(organization_id);
CREATE INDEX IF NOT EXISTS idx_inspections_org_status ON inspections(organization_id, status);

-- Triggers de Update
CREATE TRIGGER update_ai_assistants_updated_at BEFORE UPDATE ON ai_assistants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_checklist_folders_updated_at BEFORE UPDATE ON checklist_folders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_checklist_templates_updated_at BEFORE UPDATE ON checklist_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_checklist_fields_updated_at BEFORE UPDATE ON checklist_fields FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inspections_updated_at BEFORE UPDATE ON inspections FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inspection_items_updated_at BEFORE UPDATE ON inspection_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_action_items_updated_at BEFORE UPDATE ON action_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inspection_media_updated_at BEFORE UPDATE ON inspection_media FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
