-- Create calendar_events table
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by UUID REFERENCES auth.users(id),
    
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    
    event_type TEXT NOT NULL CHECK (event_type IN ('inspection', 'meeting', 'focus_time', 'blocking', 'other')),
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled', 'rescheduled')),
    
    metadata JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;

-- Create policy for users to see events from their organization
CREATE POLICY "Users can view events from their organization"
ON public.calendar_events
FOR SELECT
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

-- Create policy for users to insert events for their organization
CREATE POLICY "Users can insert events for their organization"
ON public.calendar_events
FOR INSERT
WITH CHECK (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

-- Create policy for users to update events from their organization
CREATE POLICY "Users can update events from their organization"
ON public.calendar_events
FOR UPDATE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

-- Create policy for users to delete events from their organization
CREATE POLICY "Users can delete events from their organization"
ON public.calendar_events
FOR DELETE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_calendar_events_org_id ON public.calendar_events(organization_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_start_time ON public.calendar_events(start_time);
CREATE INDEX IF NOT EXISTS idx_calendar_events_status ON public.calendar_events(status);
