-- Create action_plans table
CREATE TABLE IF NOT EXISTS public.action_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by UUID REFERENCES auth.users(id),
    
    description TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')),
    due_date TIMESTAMPTZ,
    
    inspection_id BIGINT, -- Optional link to inspection
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.action_plans ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_action_plans_org_id ON public.action_plans(organization_id);
CREATE INDEX IF NOT EXISTS idx_action_plans_status ON public.action_plans(status);
CREATE INDEX IF NOT EXISTS idx_action_plans_due_date ON public.action_plans(due_date);

-- RLS Policies
CREATE POLICY "Users can view action plans from their organization"
ON public.action_plans FOR SELECT
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can insert action plans for their organization"
ON public.action_plans FOR INSERT
WITH CHECK (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can update action plans from their organization"
ON public.action_plans FOR UPDATE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can delete action plans from their organization"
ON public.action_plans FOR DELETE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);
