-- Create inspections table
CREATE TABLE IF NOT EXISTS public.inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT REFERENCES public.organizations(id) ON DELETE CASCADE,
    created_by UUID REFERENCES auth.users(id),
    
    project_name TEXT NOT NULL,
    inspection_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'in_progress', 'completed', 'cancelled')),
    scheduled_date TIMESTAMPTZ,
    completed_date TIMESTAMPTZ,
    
    description TEXT,
    location TEXT,
    
    client_id BIGINT, -- Optional reference to clients table if exists, or just loose
    template_id BIGINT, 
    inspector_name TEXT,
    inspector_email TEXT,
    
    participants JSONB DEFAULT '[]'::jsonb,
    checklist_data JSONB DEFAULT '{}'::jsonb,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.inspections ENABLE ROW LEVEL SECURITY;

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_inspections_org_id ON public.inspections(organization_id);
CREATE INDEX IF NOT EXISTS idx_inspections_status ON public.inspections(status);
CREATE INDEX IF NOT EXISTS idx_inspections_scheduled_date ON public.inspections(scheduled_date);

-- RLS Policies
CREATE POLICY "Users can view inspections from their organization"
ON public.inspections FOR SELECT
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can insert inspections for their organization"
ON public.inspections FOR INSERT
WITH CHECK (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can update inspections from their organization"
ON public.inspections FOR UPDATE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);

CREATE POLICY "Users can delete inspections from their organization"
ON public.inspections FOR DELETE
USING (
    organization_id IN (
        SELECT organization_id FROM public.users WHERE id = auth.uid()
        UNION
        SELECT managed_organization_id FROM public.users WHERE id = auth.uid()
    )
);
